# Run manually from PowerShell. Repository policy prohibits Codex from running
# Dart/Flutter verification. This script stops at the first failing command.
$ErrorActionPreference = 'Stop'
Set-Location (Split-Path -Parent $PSScriptRoot)

$reviewSources = @(
    'lib/main.dart'
    'lib/theme/theme_extensions.dart'
    'lib/theme/neo_brutalism_theme.dart'
    'lib/theme/neo_brutalism_pilot_gallery.dart'
    'lib/theme/debug_theme_family_control.dart'
    'lib/theme/tokens/app_surface_tokens.dart'
    'lib/theme/tokens/app_tutorial_tokens.dart'
    'lib/theme/widgets/tonos_action.dart'
    'lib/theme/widgets/tonos_action_depth.dart'
    'lib/theme/widgets/tonos_dialog.dart'
    'lib/theme/widgets/tonos_surface.dart'
    'lib/theme/widgets/tonos_theme_ready.dart'
    'lib/theme/widgets/tonos_sheet.dart'
    'lib/theme/widgets/workout_actions.dart'
    'lib/theme/app_theme_capabilities.dart'
    'lib/theme/app_theme_family.dart'
    'lib/theme/app_theme_factory.dart'
    'lib/theme/app_theme_preferences.dart'
    'lib/providers/theme_provider.dart'
    'lib/providers/nutrition_profile.dart'
    'lib/utils/app_test_keys.dart'
    'lib/widgets/session_complete_sheet.dart'
    'lib/widgets/settings_tiles.dart'
    'lib/widgets/weight_card.dart'
    'lib/widgets/exercise_progress_section.dart'
    'lib/widgets/workout_metric_chart_card.dart'
    'lib/widgets/workout_history_calendar.dart'
    'lib/widgets/history_summary_widget.dart'
    'lib/widgets/preset_info_card.dart'
    'lib/widgets/preset_bar.dart'
    'lib/widgets/body_heatmap.dart'
    'lib/widgets/seven_day_focus_card.dart'
    'lib/widgets/workout_record_badges.dart'
    'lib/widgets/cardio_card.dart'
    'lib/widgets/current_metrics_section.dart'
    'lib/widgets/exercise_definition_info_tile.dart'
    'lib/widgets/nutrition_bar_details.dart'
    'lib/widgets/stretch_card.dart'
    'lib/widgets/guided_tutorial_overlay.dart'
    'lib/widgets/onboarding_plan_builder_coach.dart'
    'lib/screens/exercise/train2_page.dart'
    'lib/screens/exercise/definitions_by_bodypart_page.dart'
    'lib/screens/exercise/definitions_by_muscle_page.dart'
    'lib/screens/exercise/full_history_screen.dart'
    'lib/screens/nutrition/default_trend_page.dart'
    'lib/screens/nutrition/food_customization_page.dart'
    'lib/screens/nutrition/food_logging_page.dart'
    'lib/screens/profile/settings/goal_manual_entry_page.dart'
    'lib/screens/profile/settings/ui_appearance_settings_page.dart'
    'lib/screens/profile/settings/database_settings_page.dart'
    'lib/screens/profile/settings/bodypart_ranking_screen.dart'
    'lib/screens/profile/settings/muscle_ranking_screen.dart'
    'lib/screens/profile/settings/profile_page.dart'
    'lib/screens/profile/settings/user_information_settings_page.dart'
    'lib/screens/profile/settings/nav_bar_settings_page.dart'
    'lib/screens/profile/settings/tutorials_settings_page.dart'
    'lib/screens/profile/settings/gym_exercise_settings_page.dart'
    'lib/screens/profile/settings/analytics_setting_screen.dart'
    'lib/screens/profile/settings/exercise_analytics_screen.dart'
    'lib/screens/profile/settings/exercise_editor_screen.dart'
    'lib/screens/profile/settings/volume_boundaries_screen.dart'
    'lib/screens/profile/settings/bodypart_muscle_mapping_screen.dart'
    'lib/screens/profile/settings/flow_methods_page.dart'
    'lib/screens/profile/settings/workout_progress_flows_page.dart'
    'lib/screens/profile/settings/measurements_trends_settings_page.dart'
    'lib/screens/profile/settings/diagnostics_settings_page.dart'
    'lib/screens/profile/settings/diet_nutrition_settings_page.dart'
    'lib/screens/profile/settings/app_settings_page.dart'
    'lib/screens/exercise/exercise_catalog_page.dart'
    'lib/screens/exercise/muscle_filter_page.dart'
    'lib/screens/exercise/session_detail_screen.dart'
    'lib/screens/exercise/history_screen.dart'
    'lib/screens/exercise/auto_preset_flow_screen.dart'
    'lib/screens/catalog_page.dart'
    'lib/screens/dashboard_page.dart'
    'lib/screens/measurement_trends_page.dart'
    'lib/screens/nutrition/nutrition_page.dart'
    'lib/screens/nutrition/log_entry_page.dart'
    'lib/screens/nutrition/measured_items_page.dart'
    'lib/screens/nutrition/barcode_scanner_page.dart'
    'lib/screens/nutrition/pantry_log_page.dart'
    'lib/screens/nutrition/plan_meal_page.dart'
    'lib/services/barcode_scanner_session.dart'
    'lib/theme/widgets/media_viewer_image.dart'
    'lib/widgets/exercise_detail_sheet.dart'
    'lib/widgets/exercise_media_thumbnail.dart'
    'lib/widgets/shared_entity_media_thumbnail.dart'
    'lib/widgets/history_content.dart'
    'lib/widgets/past_sessions_list.dart'
    'lib/widgets/health_trends_section.dart'
    'lib/widgets/meal_plan_add_bar.dart'
    'lib/widgets/nutrition_text_details.dart'
)
$reviewTests = @(
    'test/theme/widgets/exercise_progress_responsive_test.dart'
    'test/theme/widgets/workout_metric_chart_card_responsive_test.dart'
    'test/theme/widgets/seven_day_focus_presentation_test.dart'
    'test/theme/widgets/neo_refinement_regression_test.dart'
    'test/theme/widgets/settings_tiles_test.dart'
    'test/theme/widgets/tonos_surface_test.dart'
    'test/theme/widgets/tonos_sheet_test.dart'
    'test/theme/theme_lab_page_test.dart'
    'test/theme/tonos_theme_ready_test.dart'
    'test/theme/pre_q2_route_evidence_test.dart'
    'test/theme/neo_brutalism_theme_test.dart'
    'test/theme/app_theme_tokens_test.dart'
    'test/theme/app_theme_capabilities_test.dart'
    'test/theme/app_theme_family_test.dart'
    'test/theme/app_theme_preferences_test.dart'
    'test/theme/debug_theme_family_control_test.dart'
    'test/theme/q2_runtime_accessibility_test.dart'
    'test/theme/e2_route_ledger_contract_test.dart'
    'test/theme/n5_route_state_contract_test.dart'
    'test/theme/settings_residue_contract_test.dart'
    'test/theme/catalog_media_contract_test.dart'
    'test/theme/dashboard_history_contract_test.dart'
    'test/theme/health_measurements_contract_test.dart'
    'test/theme/health_measurements_tokens_test.dart'
    'test/theme/media_viewer_test.dart'
    'test/theme/barcode_scanner_route_test.dart'
    'test/theme/nutrition_presentation_test.dart'
    'test/theme/tutorial_presentation_test.dart'
    'test/theme/food_logging_behavior_test.dart'
    'test/theme/nutrition_goals_behavior_test.dart'
    'test/theme/theme_family_selector_test.dart'
    'test/theme/theme_style_ratchet_test.dart'
    'test/theme/theme_style_ratchet_cli_test.dart'
    'test/widgets/responsive_accessibility_test.dart'
    'test/widgets/media_accessibility_contract_test.dart'
    'test/widgets/current_metrics_section_test.dart'
    'test/widgets/visual_layout_contract_test.dart'
    'test/widgets/localized_catalog_entity_name_test.dart'
    'test/widgets/localized_exercise_name_test.dart'
    'test/widgets/safe_error_view_test.dart'
    'test/providers/app_configuration_test.dart'
    'test/screens/measured_items_page_test.dart'
    'test/screens/onboarding_and_plan_flow_test.dart'
)
$boundaryTests = @(
    'test/providers/app_configuration_test.dart'
    'test/screens/measured_items_page_test.dart'
    'test/screens/onboarding_and_plan_flow_test.dart'
    'test/theme/e2_route_ledger_contract_test.dart'
    'test/theme/n5_route_state_contract_test.dart'
    'test/theme/settings_residue_contract_test.dart'
    'test/widgets/current_metrics_section_test.dart'
    'test/widgets/media_accessibility_contract_test.dart'
    'test/widgets/visual_layout_contract_test.dart'
    'test/widgets/localized_catalog_entity_name_test.dart'
    'test/widgets/localized_exercise_name_test.dart'
    'test/widgets/safe_error_view_test.dart'
)

dart format @reviewSources @reviewTests
if ($LASTEXITCODE -ne 0) { throw 'Formatting failed. Paste the output before proceeding.' }
dart analyze @reviewSources @reviewTests
if ($LASTEXITCODE -ne 0) { throw 'Analysis failed. Paste the output before proceeding.' }
flutter test test/theme
if ($LASTEXITCODE -ne 0) { throw 'Theme tests failed. Paste the output before proceeding.' }
flutter test test/widgets/responsive_accessibility_test.dart
if ($LASTEXITCODE -ne 0) { throw 'Responsive accessibility tests failed. Paste the output before proceeding.' }
flutter test @boundaryTests
if ($LASTEXITCODE -ne 0) { throw 'Route boundary tests failed. Paste the output before proceeding.' }
git diff --check
if ($LASTEXITCODE -ne 0) { throw 'Whitespace check failed. Paste the output before proceeding.' }
dart run tools/theme_style_ratchet.dart docs/theme-style-ratchet.json
if ($LASTEXITCODE -ne 0) { throw 'Theme style ratchet failed. Paste the output before proceeding.' }
Write-Output 'Neo refinement formatting, analysis, theme, and route-boundary tests passed.'
