import 'dart:convert';
import 'dart:io';

import 'package:crypto/crypto.dart';

Future<void> main(List<String> args) async {
  final command = args.isEmpty ? 'help' : args.first;
  final options = _CliOptions.parse(args.skip(1).toList());

  try {
    switch (command) {
      case 'build-exercise-media':
        await _buildExerciseMediaManifest(options);
        break;
      case 'validate-exercise-media':
        await _validateExerciseMediaManifest(options);
        break;
      case 'help':
      case '--help':
      case '-h':
        _printHelp();
        break;
      default:
        _fail('Unknown command "$command". Run with "help" for usage.');
    }
  } on _PipelineFailure catch (e) {
    stderr.writeln(e.message);
    exitCode = 1;
  }
}

Future<void> _buildExerciseMediaManifest(_CliOptions options) async {
  final sourcePath = options.requiredValue('source');
  final outputPath = options.requiredValue('output');
  final exerciseDefsPath =
      options.value('exercise-defs') ?? 'assets/exercises.json';
  final source = await _loadJsonMap(sourcePath);
  final exerciseIndex = await _ExerciseIndex.load(exerciseDefsPath);
  final baseUrl = options.value('base-url') ?? source.stringValue('baseUrl');
  final version =
      options.intValue('version') ?? source.intValue('version') ?? 1;
  final namespace = source.stringValue('namespace') ?? 'exercise_media';
  final checkRemote = options.flag('check-remote');
  final strict = options.flag('strict');

  final result =
      await _ExerciseMediaManifestBuilder(
        source: source,
        exerciseIndex: exerciseIndex,
        baseUrl: baseUrl,
        namespace: namespace,
        version: version,
        checkRemote: checkRemote,
      ).build();

  _printMessages(result.messages);
  if (result.hasErrors) {
    _fail('Build failed because errors were found.');
  }
  if (strict && result.hasWarnings) {
    _fail('Strict mode failed because warnings were found.');
  }

  final outputFile = File(outputPath);
  await outputFile.parent.create(recursive: true);
  const encoder = JsonEncoder.withIndent('  ');
  await outputFile.writeAsString('${encoder.convert(result.manifest)}\n');

  final uploadScriptPath = options.value('upload-script');
  if (uploadScriptPath != null) {
    final bucket = options.requiredValue('bucket');
    final manifestObject =
        options.value('manifest-object') ??
        'manifests/exercise_media_manifest.json';
    await _writeUploadScript(
      source: source,
      outputPath: outputPath,
      uploadScriptPath: uploadScriptPath,
      bucket: bucket,
      manifestObject: manifestObject,
    );
  }

  stdout.writeln(
    'Wrote ${result.assetCount} assets for ${result.exerciseCount} exercises '
    'to $outputPath.',
  );
}

Future<void> _validateExerciseMediaManifest(_CliOptions options) async {
  final sourcePath = options.requiredValue('source');
  final exerciseDefsPath =
      options.value('exercise-defs') ?? 'assets/exercises.json';
  final source = await _loadJsonMap(sourcePath);
  final exerciseIndex = await _ExerciseIndex.load(exerciseDefsPath);
  final baseUrl = options.value('base-url') ?? source.stringValue('baseUrl');
  final checkRemote = options.flag('check-remote');
  final strict = options.flag('strict');

  final result =
      await _ExerciseMediaManifestBuilder(
        source: source,
        exerciseIndex: exerciseIndex,
        baseUrl: baseUrl,
        namespace: source.stringValue('namespace') ?? 'exercise_media',
        version: options.intValue('version') ?? source.intValue('version') ?? 1,
        checkRemote: checkRemote,
      ).build();

  _printMessages(result.messages);
  if (result.hasErrors || (strict && result.hasWarnings)) {
    _fail('Validation failed.');
  }
  stdout.writeln(
    'Validated ${result.assetCount} assets for ${result.exerciseCount} exercises.',
  );
}

Future<Map<String, dynamic>> _loadJsonMap(String path) async {
  final file = File(path);
  if (!await file.exists()) {
    _fail('File not found: $path');
  }
  final decoded = jsonDecode(await file.readAsString());
  if (decoded is! Map) {
    _fail('Expected a JSON object in $path.');
  }
  return Map<String, dynamic>.from(decoded);
}

void _printMessages(List<_PipelineMessage> messages) {
  for (final message in messages) {
    final label = message.severity.name.toUpperCase();
    stdout.writeln('[$label] ${message.text}');
  }
}

Future<void> _writeUploadScript({
  required Map<String, dynamic> source,
  required String outputPath,
  required String uploadScriptPath,
  required String bucket,
  required String manifestObject,
}) async {
  final lines = <String>[
    '# Generated by tools/content_pipeline.dart.',
    '# Requires Wrangler auth: https://developers.cloudflare.com/workers/wrangler/',
    r'$ErrorActionPreference = "Stop"',
    '',
  ];

  final sourceExercises = source.listValue('exercises');
  for (final exercise in sourceExercises.whereType<Map>()) {
    final assets = Map<String, dynamic>.from(exercise).listValue('assets');
    for (final rawAsset in assets.whereType<Map>()) {
      final asset = Map<String, dynamic>.from(rawAsset);
      final localFile = asset.stringValue('localFile');
      final remotePath =
          asset.stringValue('path') ?? asset.stringValue('remotePath');
      if (localFile == null || remotePath == null) continue;
      lines.add(
        'wrangler r2 object put ${_psQuote('$bucket/$remotePath')} '
        '--file ${_psQuote(localFile)} '
        '--content-type ${_psQuote(_contentTypeFor(remotePath))}',
      );
    }
  }

  lines
    ..add(
      'wrangler r2 object put ${_psQuote('$bucket/$manifestObject')} '
      '--file ${_psQuote(outputPath)} '
      '--content-type ${_psQuote('application/json')}',
    )
    ..add('');

  final file = File(uploadScriptPath);
  await file.parent.create(recursive: true);
  await file.writeAsString(lines.join('\n'));
  stdout.writeln('Wrote upload script to $uploadScriptPath.');
}

String _psQuote(String value) => "'${value.replaceAll("'", "''")}'";

String _contentTypeFor(String path) {
  final lower = path.toLowerCase();
  if (lower.endsWith('.png')) return 'image/png';
  if (lower.endsWith('.jpg') || lower.endsWith('.jpeg')) return 'image/jpeg';
  if (lower.endsWith('.webp')) return 'image/webp';
  if (lower.endsWith('.gif')) return 'image/gif';
  if (lower.endsWith('.mp4')) return 'video/mp4';
  if (lower.endsWith('.json')) return 'application/json';
  return 'application/octet-stream';
}

void _printHelp() {
  stdout.writeln('''
Tonos content pipeline

Commands:
  build-exercise-media      Build an app-ready exercise media manifest.
  validate-exercise-media   Validate a source file without writing output.

Common options:
  --source <path>           Source JSON describing exercise media.
  --exercise-defs <path>    Exercise definitions JSON. Defaults to assets/exercises.json.
  --base-url <url>          CDN/R2 base URL. Overrides source baseUrl.
  --version <number>        Manifest version. Overrides source version.
  --check-remote            HEAD-check generated URLs.
  --strict                  Treat warnings as failures.

Build-only options:
  --output <path>           Generated manifest path.
  --upload-script <path>    Optional PowerShell upload script path.
  --bucket <name>           R2 bucket name for upload script generation.
  --manifest-object <key>   Manifest object key. Defaults to manifests/exercise_media_manifest.json.

Example:
  dart run tools/content_pipeline.dart build-exercise-media --source tools/content_pipeline/exercise_media_source.example.json --output build/content/exercise_media_manifest.json --check-remote
''');
}

Never _fail(String message) => throw _PipelineFailure(message);

class _PipelineFailure implements Exception {
  final String message;

  const _PipelineFailure(this.message);
}

class _CliOptions {
  final Map<String, String> _values;
  final Set<String> _flags;

  const _CliOptions(this._values, this._flags);

  factory _CliOptions.parse(List<String> args) {
    final values = <String, String>{};
    final flags = <String>{};

    for (var i = 0; i < args.length; i++) {
      final arg = args[i];
      if (!arg.startsWith('--')) {
        _fail('Unexpected argument: $arg');
      }
      final key = arg.substring(2);
      if (key.isEmpty) _fail('Empty option name.');

      final hasValue = i + 1 < args.length && !args[i + 1].startsWith('--');
      if (hasValue) {
        values[key] = args[++i];
      } else {
        flags.add(key);
      }
    }

    return _CliOptions(values, flags);
  }

  String? value(String key) => _values[key];

  String requiredValue(String key) {
    final result = value(key);
    if (result == null || result.trim().isEmpty) {
      _fail('Missing required option --$key.');
    }
    return result;
  }

  int? intValue(String key) {
    final raw = value(key);
    if (raw == null) return null;
    final parsed = int.tryParse(raw);
    if (parsed == null) _fail('Expected --$key to be an integer.');
    return parsed;
  }

  bool flag(String key) => _flags.contains(key);
}

class _ExerciseMediaManifestBuilder {
  _ExerciseMediaManifestBuilder({
    required this.source,
    required this.exerciseIndex,
    required this.baseUrl,
    required this.namespace,
    required this.version,
    required this.checkRemote,
  });

  final Map<String, dynamic> source;
  final _ExerciseIndex exerciseIndex;
  final String? baseUrl;
  final String namespace;
  final int version;
  final bool checkRemote;

  final List<_PipelineMessage> _messages = [];
  final Set<int> _seenExerciseIds = {};
  final Set<String> _seenAssetIds = {};

  Future<_BuildResult> build() async {
    final outputExercises = <Map<String, dynamic>>[];
    var assetCount = 0;

    for (final rawExercise in source.listValue('exercises')) {
      if (rawExercise is! Map) {
        _error('Skipping exercise entry because it is not an object.');
        continue;
      }
      final exercise = Map<String, dynamic>.from(rawExercise);
      final resolved = _resolveExercise(exercise);
      if (resolved == null) continue;

      if (!_seenExerciseIds.add(resolved.id)) {
        _error('Duplicate exerciseId ${resolved.id} (${resolved.name}).');
        continue;
      }

      final assets = <Map<String, dynamic>>[];
      var assetIndex = 0;
      for (final rawAsset in exercise.listValue('assets')) {
        if (rawAsset is! Map) {
          _error(
            'Skipping asset for ${resolved.name}; asset is not an object.',
          );
          continue;
        }
        final builtAsset = await _buildAsset(
          Map<String, dynamic>.from(rawAsset),
          exercise: resolved,
          assetIndex: assetIndex,
        );
        assetIndex += 1;
        if (builtAsset == null) continue;
        assets.add(builtAsset);
      }

      if (assets.isEmpty) {
        _warning('No valid assets found for ${resolved.name}.');
        continue;
      }

      assetCount += assets.length;
      outputExercises.add({
        'exerciseId': resolved.id,
        'slug': exercise.stringValue('slug') ?? _slugify(resolved.name),
        'assets': assets,
      });
    }

    outputExercises.sort(
      (a, b) => (a['exerciseId'] as int).compareTo(b['exerciseId'] as int),
    );

    return _BuildResult(
      manifest: {
        'namespace': namespace,
        'version': version,
        'generatedAt': DateTime.now().toUtc().toIso8601String(),
        'exercises': outputExercises,
      },
      messages: List.unmodifiable(_messages),
      exerciseCount: outputExercises.length,
      assetCount: assetCount,
    );
  }

  _ResolvedExercise? _resolveExercise(Map<String, dynamic> exercise) {
    final id = exercise.intValue('exerciseId');
    final name =
        exercise.stringValue('exerciseName') ?? exercise.stringValue('name');

    if (id == null && name == null) {
      _error('Exercise entry needs exerciseId or exerciseName.');
      return null;
    }

    final byId = id == null ? null : exerciseIndex.byId(id);
    final byName = name == null ? null : exerciseIndex.byName(name);

    if (id != null && byId == null) {
      _error('Unknown exerciseId $id.');
      return null;
    }
    if (name != null && byName == null) {
      _error('Unknown exerciseName "$name".');
      return null;
    }
    if (byId != null && byName != null && byId.id != byName.id) {
      _error(
        'Exercise mismatch: id ${byId.id} is "${byId.name}" but name "$name" '
        'resolves to id ${byName.id}.',
      );
      return null;
    }

    final resolved = byId ?? byName;
    if (resolved == null) return null;
    if (name != null && resolved.name != name) {
      _warning(
        'Exercise name casing differs for id ${resolved.id}: source "$name", '
        'definitions "${resolved.name}".',
      );
    }
    return resolved;
  }

  Future<Map<String, dynamic>?> _buildAsset(
    Map<String, dynamic> asset, {
    required _ResolvedExercise exercise,
    required int assetIndex,
  }) async {
    final slug = _slugify(exercise.name);
    final mediaType = asset.stringValue('type') ?? 'image';
    final assetVersion = asset.intValue('version') ?? 1;
    final assetId =
        asset.stringValue('assetId') ??
        '${slug}_${mediaType}_v${assetVersion}_$assetIndex';

    if (!_seenAssetIds.add(assetId)) {
      _error('Duplicate assetId "$assetId".');
      return null;
    }

    final url = _assetUrl(asset, key: 'url');
    if (url == null) {
      _error('Asset "$assetId" needs url, path, or remotePath.');
      return null;
    }
    final thumbnailUrl = _assetUrl(asset, key: 'thumbnailUrl') ?? url;

    final output = <String, dynamic>{
      'assetId': assetId,
      'type': mediaType,
      'url': url,
      'thumbnailUrl': thumbnailUrl,
      'title': asset.stringValue('title') ?? exercise.name,
      'sortOrder': asset.intValue('sortOrder') ?? assetIndex,
      'version': assetVersion,
    };

    final localFile = asset.stringValue('localFile');
    if (localFile != null) {
      await _addLocalFileMetadata(output, localFile, assetId);
    }

    _copyOptionalInt(asset, output, 'bytes');
    _copyOptionalInt(asset, output, 'width');
    _copyOptionalInt(asset, output, 'height');
    _copyOptionalString(asset, output, 'sha256');
    _copyOptionalString(asset, output, 'licenseId');

    if (checkRemote) {
      await _checkRemoteUrl(
        url,
        assetId,
        expectedBytes: output['bytes'] as int?,
      );
      if (thumbnailUrl != url) {
        await _checkRemoteUrl(thumbnailUrl, '$assetId thumbnail');
      }
    }

    return output;
  }

  Future<void> _addLocalFileMetadata(
    Map<String, dynamic> output,
    String localFile,
    String assetId,
  ) async {
    final file = File(localFile);
    if (!await file.exists()) {
      _error('Local file for "$assetId" does not exist: $localFile');
      return;
    }

    final bytes = await file.readAsBytes();
    output['bytes'] = bytes.length;
    output['sha256'] = sha256.convert(bytes).toString();
  }

  String? _assetUrl(Map<String, dynamic> asset, {required String key}) {
    final explicit = asset.stringValue(key);
    if (explicit != null) return explicit;

    final pathKeys =
        key == 'thumbnailUrl'
            ? const ['thumbnailPath']
            : const ['path', 'remotePath'];
    for (final pathKey in pathKeys) {
      final path = asset.stringValue(pathKey);
      if (path != null) {
        if (baseUrl == null || baseUrl!.trim().isEmpty) {
          _error('Asset path "$path" needs baseUrl.');
          return null;
        }
        return _joinUrl(baseUrl!, path);
      }
    }
    return null;
  }

  Future<void> _checkRemoteUrl(
    String url,
    String label, {
    int? expectedBytes,
  }) async {
    final uri = Uri.tryParse(url);
    if (uri == null || !uri.hasScheme || uri.host.isEmpty) {
      _error('Invalid URL for "$label": $url');
      return;
    }

    final client = HttpClient();
    try {
      final response = await _openHeadOrGet(client, uri);
      final status = response.statusCode;
      final length = response.contentLength;
      await response.drain<void>();
      if (status < 200 || status >= 400) {
        _error('URL check failed for "$label": HTTP $status $url');
      } else if (expectedBytes != null &&
          length > 0 &&
          length != expectedBytes) {
        _warning(
          'Remote byte count for "$label" is $length, expected $expectedBytes.',
        );
      }
    } catch (e) {
      _error('URL check failed for "$label": $e');
    } finally {
      client.close(force: true);
    }
  }

  Future<HttpClientResponse> _openHeadOrGet(HttpClient client, Uri uri) async {
    final head = await client.headUrl(uri);
    final headResponse = await head.close();
    if (headResponse.statusCode != 405) return headResponse;
    await headResponse.drain<void>();

    final get = await client.getUrl(uri);
    return get.close();
  }

  void _copyOptionalInt(
    Map<String, dynamic> source,
    Map<String, dynamic> output,
    String key,
  ) {
    final value = source.intValue(key);
    if (value != null) output[key] = value;
  }

  void _copyOptionalString(
    Map<String, dynamic> source,
    Map<String, dynamic> output,
    String key,
  ) {
    final value = source.stringValue(key);
    if (value != null) output[key] = value;
  }

  void _error(String text) => _messages.add(_PipelineMessage.error(text));

  void _warning(String text) => _messages.add(_PipelineMessage.warning(text));
}

class _ExerciseIndex {
  final Map<int, _ResolvedExercise> _byId;
  final Map<String, _ResolvedExercise> _byName;

  const _ExerciseIndex(this._byId, this._byName);

  static Future<_ExerciseIndex> load(String path) async {
    final raw = await File(path).readAsString();
    final decoded = jsonDecode(raw);
    if (decoded is! List) {
      _fail('Expected a JSON list in $path.');
    }

    final byId = <int, _ResolvedExercise>{};
    final byName = <String, _ResolvedExercise>{};

    for (var i = 0; i < decoded.length; i++) {
      final item = decoded[i];
      if (item is! Map) continue;
      final name = Map<String, dynamic>.from(item).stringValue('name');
      if (name == null) continue;
      final exercise = _ResolvedExercise(id: i + 1, name: name);
      byId[exercise.id] = exercise;
      byName[_normalizeName(name)] = exercise;
    }

    return _ExerciseIndex(byId, byName);
  }

  _ResolvedExercise? byId(int id) => _byId[id];

  _ResolvedExercise? byName(String name) => _byName[_normalizeName(name)];
}

class _ResolvedExercise {
  final int id;
  final String name;

  const _ResolvedExercise({required this.id, required this.name});
}

class _BuildResult {
  final Map<String, dynamic> manifest;
  final List<_PipelineMessage> messages;
  final int exerciseCount;
  final int assetCount;

  const _BuildResult({
    required this.manifest,
    required this.messages,
    required this.exerciseCount,
    required this.assetCount,
  });

  bool get hasErrors =>
      messages.any((message) => message.severity == _Severity.error);

  bool get hasWarnings =>
      messages.any((message) => message.severity == _Severity.warning);
}

class _PipelineMessage {
  final _Severity severity;
  final String text;

  const _PipelineMessage(this.severity, this.text);

  factory _PipelineMessage.error(String text) {
    return _PipelineMessage(_Severity.error, text);
  }

  factory _PipelineMessage.warning(String text) {
    return _PipelineMessage(_Severity.warning, text);
  }
}

enum _Severity { error, warning }

extension _JsonMapTools on Map<String, dynamic> {
  String? stringValue(String key) {
    final value = this[key];
    if (value == null) return null;
    final text = value.toString().trim();
    return text.isEmpty ? null : text;
  }

  int? intValue(String key) {
    final value = this[key];
    if (value is int) return value;
    if (value is num) return value.toInt();
    if (value is String) return int.tryParse(value.trim());
    return null;
  }

  List<dynamic> listValue(String key) {
    final value = this[key];
    if (value is List) return value;
    return const [];
  }
}

String _joinUrl(String baseUrl, String path) {
  final cleanBase =
      baseUrl.endsWith('/')
          ? baseUrl.substring(0, baseUrl.length - 1)
          : baseUrl;
  final cleanPath = path.startsWith('/') ? path.substring(1) : path;
  return '$cleanBase/$cleanPath';
}

String _slugify(String value) {
  final lower = value.toLowerCase();
  final buffer = StringBuffer();
  var previousWasSeparator = false;

  for (final codeUnit in lower.codeUnits) {
    final isLetterOrNumber =
        (codeUnit >= 97 && codeUnit <= 122) ||
        (codeUnit >= 48 && codeUnit <= 57);
    if (isLetterOrNumber) {
      buffer.writeCharCode(codeUnit);
      previousWasSeparator = false;
    } else if (!previousWasSeparator) {
      buffer.write('_');
      previousWasSeparator = true;
    }
  }

  return buffer.toString().replaceAll(RegExp(r'^_+|_+$'), '');
}

String _normalizeName(String value) => value.trim().toLowerCase();
